### ISSUE TITLE
Alert / Error styles

### ISSUE THREAD

**Issue by dhcole** [18F/federalist-design#7]
@goodnightjj could we get some guidance for styling error messages? Here are two examples:

<img width="1247" alt="screen shot 2016-01-15 at 4 29 01 pm" src="https://cloud.githubusercontent.com/assets/170641/12365820/35494576-bba5-11e5-93fb-ac254509cffe.png">

<img width="1093" alt="screen shot 2016-01-15 at 4 28 53 pm" src="https://cloud.githubusercontent.com/assets/170641/12365828/3c7c9bc2-bba5-11e5-9cf6-8bdae9e0eb61.png">

In the second case we're using the [web standards alerts](https://playbook.cio.gov/designstandards/alerts/), though on our site, the images are broken.

<img width="870" alt="screen shot 2016-01-15 at 4 30 26 pm" src="https://cloud.githubusercontent.com/assets/170641/12365847/629e4904-bba5-11e5-9414-c3d01ec6f734.png">

Should we fix the icons on the alerts and implement these messages exactly as they appear in the web standards, or do you have another idea of how they should look?

**Comment by goodnightjj** [comment]
i went for a white background with colored border for a cleaner look and better legibility. i also see the icons here are not so useful because the undifferentiate-able between information, warning, and error.

https://github.com/18F/federalist-design/blob/master/visual/guidelines/ui-styleguide.md#alerts
